name: Azure Static Web Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Upload to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: frontend
          skip_app_build: true
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
